# Generated by Django 3.1.3 on 2020-11-20 01:34

import customer_service.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mark', models.CharField(max_length=50, verbose_name='Mark')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('registration_place', models.CharField(max_length=50, verbose_name='Registration Place')),
                ('registration_country', django_countries.fields.CountryField(default='UA', max_length=2)),
                ('registration_number', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('vin_code', models.CharField(max_length=17, verbose_name='VIN code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('ind_number', models.CharField(max_length=10, unique=True, verbose_name='Individual identification number')),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('customer_type', models.CharField(choices=[('Ф', 'Individual entity'), ('Ю', 'Legal entity')], default='Ф', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='data_file/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Data File',
                'verbose_name_plural': 'Data Files',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, verbose_name='Policy number')),
                ('sticker', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insurance_code', customer_service.models.IntegerRangeField()),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bonus', models.CharField(blank=True, max_length=1, null=True)),
                ('territory', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.car', verbose_name='Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Polices',
            },
        ),
    ]
