# Generated by Django 3.1.3 on 2020-11-15 22:05

import customer_service.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50, verbose_name='Mark')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('registration_place', models.CharField(max_length=50, verbose_name='Registration Place')),
                ('registration_country', django_countries.fields.CountryField(default='UA', max_length=2)),
                ('registration_number', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('vin_code', models.CharField(max_length=17, verbose_name='VIN code')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Policy number')),
                ('sticker', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insurance_code', customer_service.models.IntegerRangeField()),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bonus', models.CharField(blank=True, max_length=1, null=True)),
                ('territory', models.TextField()),
                ('creating_record_date', models.DateTimeField(auto_now_add=True)),
                ('updating_record_date', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Polices',
            },
        ),
    ]
