# Generated by Django 3.1.3 on 2020-11-16 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='data_file/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='creating_record_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='updating_record_date',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
