# Generated by Django 3.1.3 on 2021-01-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_auto_20210103_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesms',
            options={'verbose_name': 'Message SMS', 'verbose_name_plural': 'Messages SMS'},
        ),
    ]
