# Generated by Django 3.1.3 on 2020-11-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_auto_20201116_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': 'Data File', 'verbose_name_plural': 'Data Files'},
        ),
    ]
