# Generated by Django 3.1.3 on 2021-01-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_auto_20210104_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesms',
            old_name='Sid',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagesms',
            name='user',
        ),
    ]
