# Generated by Django 3.1.3 on 2021-01-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0006_auto_20210104_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='sms',
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_service.messagesms'),
        ),
    ]
