# Generated by Django 3.1.3 on 2021-01-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0007_auto_20210105_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesms',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_service.messagesms'),
        ),
    ]
