# Generated by Django 3.1.3 on 2021-01-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0008_messagesms_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesms',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_service.insurancepolicy'),
        ),
    ]
