# Generated by Django 3.1.3 on 2021-01-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0009_auto_20210105_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesms',
            old_name='policy',
            new_name='insurance_policy',
        ),
    ]
