# Generated by Django 3.1.3 on 2021-01-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0010_auto_20210105_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='sms',
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='sms',
            field=models.ManyToManyField(blank=True, to='customer_service.MessageSms'),
        ),
        migrations.AlterField(
            model_name='messagesms',
            name='insurance_policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer_service.insurancepolicy'),
            preserve_default=False,
        ),
    ]
