# Generated by Django 3.1.3 on 2021-01-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0015_auto_20210113_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='sid',
            field=models.CharField(default='SM3363da95c73640adb99df67151b07cf7DD', max_length=34, unique=True),
        ),
    ]
