# Generated by Django 3.1.3 on 2021-03-02 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0017_auto_20210128_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': 'Файл з даними', 'verbose_name_plural': 'Файли з даними'},
        ),
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'verbose_name': 'Страховий поліс', 'verbose_name_plural': 'Страхові поліси'},
        ),
        migrations.AlterModelOptions(
            name='messagesmsinsurancepolicyexpires',
            options={'ordering': ['-created'], 'verbose_name': 'SMS повідомлення', 'verbose_name_plural': 'SMS повідомлення'},
        ),
        migrations.AddField(
            model_name='car',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datafile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagesmsinsurancepolicyexpires',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=50, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=50, verbose_name='Реєстраційний номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_place',
            field=models.CharField(max_length=50, verbose_name='Місце реєстрації'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Ф', 'Фізична особа'), ('Ю', 'Юридична особа')], default='Ф', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ind_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Індивідуальний податковий номер'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='begin_date',
            field=models.DateField(verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.car', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.customer', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='end_date',
            field=models.DateField(verbose_name='Дата зак.'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_called_will_insure',
            field=models.BooleanField(default=False, verbose_name='Додзвонились і буде страхувати'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_called_will_not_insure',
            field=models.BooleanField(default=False, verbose_name='Додзвонились і не буде страхувати'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_impossible_to_call',
            field=models.BooleanField(default=False, verbose_name='Неможливо додзвонитись'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_reinsured',
            field=models.BooleanField(default=False, verbose_name='Застрах.'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_reinsured_another_company',
            field=models.BooleanField(default=False, verbose_name='Застраховано в іншій компанії'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Номер полісу'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='registration_date',
            field=models.DateField(verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='body',
            field=models.TextField(verbose_name='Тіло повідомлення'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='insurance_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.insurancepolicy', verbose_name='Страховий поліс'),
        ),
    ]
