# Generated by Django 3.1.3 on 2021-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0005_auto_20210104_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='sms',
            field=models.ManyToManyField(blank=True, to='customer_service.MessageSms'),
        ),
    ]
