# Generated by Django 3.1.3 on 2021-01-07 23:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0012_auto_20210107_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='from_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=('+12518508503',), max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='to_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA'),
        ),
    ]
