# Generated by Django 3.1.3 on 2021-01-08 00:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0013_auto_20210108_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesmsinsurancepolicyexpires',
            name='car',
        ),
        migrations.RemoveField(
            model_name='messagesmsinsurancepolicyexpires',
            name='customer',
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='from_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12518508503', max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='to_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+380962080624', max_length=128, region='UA'),
        ),
    ]
