# Generated by Django 3.1.3 on 2021-01-28 02:06

import customer_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0016_auto_20210114_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='sid',
            field=models.CharField(default=customer_service.utils.get_uuid_for_sms, max_length=50, unique=True),
        ),
    ]
