# Generated by Django 3.1.3 on 2021-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0019_auto_20210308_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(max_length=30, verbose_name='VIN code'),
        ),
    ]
