# Generated by Django 3.1.3 on 2021-03-13 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0020_auto_20210309_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': 'Data File', 'verbose_name_plural': 'Data Files'},
        ),
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'verbose_name': 'Insurance Policy', 'verbose_name_plural': 'Insurance Polices'},
        ),
        migrations.AlterModelOptions(
            name='messagesmsinsurancepolicyexpires',
            options={'ordering': ['-created'], 'verbose_name': 'SMS messages', 'verbose_name_plural': 'SMS messages'},
        ),
        migrations.AlterField(
            model_name='car',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=50, verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=50, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_place',
            field=models.CharField(max_length=50, verbose_name='Registration Place'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Ф', 'Individual entity'), ('Ю', 'Legal entity')], default='Ф', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ind_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Individual identification number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='begin_date',
            field=models.DateField(verbose_name='Begin date'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.car', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_called_will_insure',
            field=models.BooleanField(default=False, verbose_name='Was called and will insure'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_called_will_not_insure',
            field=models.BooleanField(default=False, verbose_name='Was called and will not insure'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_impossible_to_call',
            field=models.BooleanField(default=False, verbose_name='Impossible to call'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_reinsured',
            field=models.BooleanField(default=False, verbose_name='Insured'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='is_reinsured_another_company',
            field=models.BooleanField(default=False, verbose_name='Insured in another company'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Policy number'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='registration_date',
            field=models.DateField(verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='body',
            field=models.TextField(verbose_name='Message body'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='insurance_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_service.insurancepolicy', verbose_name='Insurance Policy'),
        ),
        migrations.AlterField(
            model_name='messagesmsinsurancepolicyexpires',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
