version: "3"

services:
  web:
    build:
      context: ./backend
    container_name: insurer_web_dev
    entrypoint:  ["python", "docker-entrypoint.dev.py"]
    volumes:
      - ./backend:/usr/src/insurer
    ports:
      - 8000:8000
    env_file:
      - .dev.env
      - .twilio.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db_dev
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .dev.env

volumes:
  postgresql_data:
